### ISSUE TITLE
Add Integer Program for the Zero Forcing Number 

### ISSUE THREAD

**Issue by RandyRDavila** [RandyRDavila/GraphProperties.jl#12]
There exists integer programming formulations for the zero forcing number. This issue is all about adding this to our code base. @bbrimkov this might be a good issue for you to connect with @joshyaffee on.

**Comment by joshyaffee** [comment]
Have you found this IP formulation anywhere in the literature? My immediate thought of how to approach finding Z(G) was Dynamic Programming, but it seems difficult.

**Comment by joshyaffee** [comment]
Added. We suspect an issue with HiGHS for the large instance identified
