### ISSUE TITLE
Add Documentation with Documenter.jl

### ISSUE THREAD

**Issue by RandyRDavila** [RandyRDavila/GraphProperties.jl#14]
Documentation is crucial for wide spread adoption of a package in Julia (I won't even try a package that doesn't have docs). So we definitely need to add this before trying to register this package.

**Comment by RandyRDavila** [comment]
@joshyaffee considering the state of the package, we should probably look into documenting it. This will be a pain in the ass figuring out how to appropriately add documentation, but will be good for you to work through and actually write on. You can use my other package [GraphCommunities.jl](https://github.com/RandyRDavila/GraphCommunities.jl) as a template. Click on the docs button and explore to see how I organized it. This should be your top priority until we get basic docs up

**Comment by joshyaffee** [comment]
Starting point for documentation created.
